# Example file for Sun workstation running Solaris
# Search path.

set spath = (/usr /usr/ucb /usr/bin)
set upath = ($HOME/bin /usr/esru/bin /usr/esru/esp-r/bin /usr/esru/bin/radiance)
set path = (. $spath $upath)

# Library path.

setenv LD_LIBRARY_PATH "/usr/esru/esp-r/lib"

# Set for all shells.

limit coredumpsize 0
set noclobber
umask 022
alias h history
unset autologout
set history=32
set filec
set savehist = 40
