#! /bin/sh

SALT=$1
RSAZI=$2
QDIRILL=$3
QDIFILL=$4
ZONE=$5
BLIND=$6

# Enter here the problem name:
NAME="1Cou"

echo "Generating sky with: SALT = $SALT, RSAZI = $RSAZI"
echo "                     QDIRILL = $QDIRILL, QDIFILL = $QDIFILL"

gendaylit -ang $1 $2 -L $3 $4 -g .10 > $NAME.sky

if [ $BLIND = 0 ]
then
   oconv $NAME.sky $NAME.mat $NAME-out.rad- $NAME-in.rad $NAME-glz.rad > $NAME.oct

else
   oconv $NAME.sky $NAME.mat $NAME-out.rad- $NAME-in.rad $NAME-glz_a.rad > $NAME.oct

fi

echo "Calculating sensor internal illuminance"

rtrace -h -I -ab 1 -ar 16 -aa .15 -ad 1024 -as 512 1Cou.oct < 1Cou.slc \
| rcalc -e '$1=(0.265*$1+0.670*$2+0.065*$3)*179' > point.illum

echo "Passing information to ESP-r"
