#!/bin/csh
# create a link in Users $HOME/bin to current esp-r executables
# so can use ESP-r. FIRST you need to set environment variable HOME
# use command HOME=/home/fred  then export HOME
echo "current home folder is " $HOME 
echo "use is"
echo "link_to [folder with exectables]"
foreach i ( aco bps c2e cfg clm dfs e2r ecnv eco grd ish mfs mld mrt pdb prj pro res tdf viewer )
  if ( -f $1/$i )then
    if ( -f $HOME/bin/$i ) rm -f $HOME/bin/$i
    ln -s $1/$i $HOME/bin/$i
    echo $i " is now pointing to "$1/$i
  endif
end
