#!/bin/bash -f

echo " "
echo "This script installs the X11 or GTK ESP-r distribution version 11.3"
echo "on a Windows computer which already has the Cygwin emulation"
echo "environment up and running."
echo " "
echo "The installation includes ESP-r executables, example models"
echo "and standard databases."
echo " "
echo "Consider being Administrator when running this installer"
echo "(or a user who has administrative privilages)."
echo " "
echo "The installation will be to a standard location, which"
echo "is /home/esru and a link will be created to this from "
echo "/usr/esru if it does not already exist."
echo " "

DSP1=" \n
 The installer works better if you are Administrator or at\n
 least have Administrator privilegegs. Consider\n
 a re-login as Administrator ;-)\n"
DSP2=" \n
 Hit return to start reading the licence\n
 \n"
DSP3=" \n
 The type of computer does not match this precompiled\n
 distribution of ESP-r. Aborting...\n"
DSP4=" \n
 The Cygiwn PATH environment variable is being updated. The .profile\n
 file the PATH= line should include the following...\n
 :/usr/esru/bin:/usr/esru/esp-r/bin\n
 \n
 and the Radiance RAYPATH environment variable has also\n
 been set.\n
 \n
 Once you have completed the install logout and then\n
 login as a normal user and start a graphic command\n
 window (you can do this via startxwin.sh or startxwin.bat.\n
 And in that command window issue the command 'prj'\n
 (without the quotes). If the installation was successful\n
 you should find that the Project Manager application\n
 has started up. If it does then you can\n
 remove this installer.\n"
DSP5=" \n
    ESP-r is free software; you can redistribute it and/or modify\n
    it under the terms of the GNU General Public License as published by\n
    the Free Software Foundation; either version 2 of the License, or\n
    (at your option) any later version.\n
    \n
    This program is distributed in the hope that it will be useful,\n
    but WITHOUT ANY WARRANTY; without even the implied warranty of\n
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n
    GNU General Public License for more details.\n
    \n
    You should have received a copy of the GNU General Public License\n
    along with this program; if not, write to the Free Software\n
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA\n
    \n"    

ISD=`pwd`

USR=`whoami`
echo " User = $USR"
if [ $USR != "Administrator" ]; then
	echo -e $DSP1
fi

echo
echo -n " proceed to install (y/n) ? "
read x

if [[ "$x" != "y" ]]
then
	echo -e " You have chosen to terminate the installation\n"
	exit
fi

echo -e $DSP2

read x
echo -e $DSP5 
echo " "
echo -n " Do you agree to the above license terms? [y/n]: "
read x

if [[ $x != 'y' ]] ; then
	echo " If you do not agree to the license, you can't install this software !"
	exit
fi

#-----------------------------------------------------------
# Detect architecture
#-----------------------------------------------------------
echo " Checking computer operating system..."
architecture=`uname -s`      # machine type
if [ $architecture = "CYGWIN_NT-5.0" ]; then
 echo "Cygwin detected - continuing..."
elif [ $architecture = "CYGWIN_NT-5.1" ]; then
 echo "Cygwin detected - continuing..."
elif [ $architecture = "CYGWIN_NT-5.2" ]; then
 echo "Cygwin detected - continuing..."
else
 echo -e $DSP2
 exit
fi

# proceed to install, first ask user which version.
echo " "
echo " ESP-r is available in two versions:"
echo " a) the standard X11 implementation"
echo " b) an implementation using the GTK graphics"
echo "    library which should be treated as a beta version"
echo "    because a few functions have not been ported."
echo " "
echo " select option [a/b]:"
read which
if [[ $which = 'a' ]] ; then
  echo "proceeding with the X11 version..."
elif  [[ $which = 'b' ]] ; then
  echo "proceeding with the GTK version..."
else
 echo "did not understand your response....aborting."
 exit
fi

# Check that necessary folders exist.
if [ ! -d /home/esru ]; then
  mkdir /home/esru
fi
  
cd /home/esru
if [[ $which = 'a' ]] ; then
  echo " Extracting X11 ESP-r distribution ..."
  zcat $ISD/esp-r_v11.3_X11_cygwin.tar.gz | tar xf - 
  echo " Extracting ESP-r distribution ...done."
  echo "copy helper applications..."
  cp $ISD/xv.exe /bin
  cp $ISD/bggen.exe /bin
  cp $ISD/xvpictoppm.exe /bin
  echo "copy helper applications... done."
elif  [[ $which = 'b' ]] ; then
  echo "proceeding with the GTK version..."
  echo " Extracting GTK ESP-r distribution ..."
  zcat $ISD/esp-r_v11.3_GTK_cygwin.tar.gz | tar xf - 
  echo " Extracting ESP-r distribution ...done."
fi
echo " "
echo "Creating a link to the ESP-r distribution... "
ln -s /home/esru /usr/esru
echo "Setting folder permissions... "
chmod a+x /home/esru
chmod a+x /home/esru/bin
chmod a+x /home/esru/esp-r
chmod a+x /home/esru/esp-r/bin
chmod a+r /home/esru
chmod a+r /home/esru/bin
chmod a+r /home/esru/esp-r
chmod a+r /home/esru/esp-r/bin

cd /
echo " Extracting Radiance distribution ..."
zcat $ISD/cygwin_rad_local_1004.tar.gz | tar xf -
echo " Extracting Radiance distribution ... done."

echo "copy and backup profile..."
cp /etc/profile /etc/profile-
cp $ISD/new_profile /etc/profile
echo "copy and backup profile... done."

echo " "
echo "Assuming your PC has all the users setup for Windows "
echo "issue the following two commands to ensure that each can use cygwin: "
echo " mkgroup -l >/etc/group "
echo " imkpasswd -l >/etc/passwd "
echo " "

cp $ISD/the_dots.tar /home/esru
cd /home/esru
tar xf the_dots.tar

echo "...done. "
echo -e $DSP4

cd $ISD

echo " "
echo -n " Please wait while the installer performs cleanup..."
for i in `ls /usr/esru/esp-r/bin`; do echo -n .; sleep 0.5; done;


