exec >$HOME/.x11startlog 2>$HOME/.x11startlog 
xsetroot -bitmap .esru.x
xterm -name Console -C -g 90X8+0+0 &
xterm -name Xterm1 -g 90X55+0-0 &
xterm -name Xterm2 -iconic -g 80X24+555-100 &
xterm -name Xterm3 -iconic -g 80X24+555-0 &
xcalc -iconic -g 155X195-180+0 &
#xmail -iconic -g 650X700+400-50 &
xclock -g 75X75-90+0 &
#xten -lib -fb 200 50 800 850
twm
