#!/bin/bash

architecture=`uname -s`      # computer type e.g. Linux Darwin SunOS

debug=""

if [ "$architecture" != "CYGWIN_NT-6.1" ]; then
   debug="--extra-debug";
fi

./Install $1 --xml --X11 --no_dbs --no_training $debug --gcc4 --silent
