#!/bin/csh -fb
#
# USAGE:
#   src2html
#
# This will create an html version of the code in the folder ../esp-r_html
#
#
# NOTES:
# src2html works on LINUX boxes. The version of awk and nawk 
# native to Solaris boxes is not able to process the script.
#
#
# src2html will create a parallel folder structure with the same
# folder names as the esp-r source distribution and with one html
# file for each *.F file in the esp-r distribution.
#
#
# Now process the esp-r source distribution...
#
# Create html version of code
#
# Get a listing of subroutine names and the files they are in.
rm -rf /tmp/esp-r.subroutines
egrep -i subroutine */*.F | \
  awk '($2=="subroutine"||$2=="SUBROUTINE") {print $0}'| \
  cut -d '(' -f 1 | sort -u | awk '{print $0," "}' > /tmp/esp-r.subroutines
egrep -i void lib/esru_x.c | \
  awk '($1=="void"||$1=="VOID") {print $0}'| \
  cut -d '(' -f 1 | sort -u | awk '{print "lib/esru_x.c: ",$0," "}' >> /tmp/esp-r.subroutines
#
# Remove current html files and create esp-r_html directory strsrc2html4ucture
#
rm -rf ../esp-r_html
mkdir ../esp-r_html
mkdir ../esp-r_html/lib
mkdir ../esp-r_html/cetc
foreach i (esru???)
mkdir ../esp-r_html/$i
end
#
# Get a listing of common block names and the files they are in. Script
# assumes it will find a file called common_list which docuements
# the common blocks in Src/esp-r.
#
set comlist="FALSE"
if (-f "common_list") then
  set comlist="TRUE"
  awk 'BEGIN{printf("<HTML>\n<BODY>\n<PRE>\n")}\
{if ($2=="DOCUMENT") {print $0,"<A name="toupper($3)">"}\
 else {print $0}} END{printf("</PRE>\n")}' common_list > ../esp-r_html/common_list.html
endif
#
# Create html files for the esp-r source distribution...
#
foreach i (*/*.F lib/esru_x.c)
awk -f ./bin/src2html.awk -v comlist=$comlist $i > ../esp-r_html/$i{.html}
end
# tidy up
rm -rf /tmp/esp-r.subroutines
