C   INCLUDE FILE;  VIEWER.h
C...GENERAL COMMON BLOCKS FOR VIEWER

      COMMON/BGEN/BILDX,BILDY,NPCAL,NPTEK,IOUTD,SCFXY,
     &              INO,ISTAT,MODEL,NAMSET,IPLN,
     &              BBBB(3),CCCC(3),DDDD(3),IPROJ,SYNVKL,
     &              NTRAT,FL,EF,
     &              XMX,XMN,YMX,YMN,ZMX,ZMN,XORG,YORG,SCAL,
     &              ZMNP,ZMXP,ISTERE,DISTE,IFREC

C      COMMON/NNAAMM/ NAMDS,NAMPIC
C      CHARACTER*30 NAMDS
C      CHARACTER*40 NAMPIC
