C     PARAMETERS FOR PLYLIB ROUTINES


C     MIP -  MAXIMUM NUMBER OF POLYGONS IN SUPERPOLYGON STRUCTURE
C     MPL -  MAXIMUM LENGTH OF SUPERPOLYGON STRUCTURE
C     MTV -  MAXIMUM NUMBER OF VERTICES IN INDIVIDUAL POLYGON
C     DELTA -  TOLERENCE FOR ADJACENT POINTS
C     IDBUG -  DEBUG FLAG  0 = NO , 1 = YES


      PARAMETER  (MIP=100,MPL=1000,MVT=300,DELTA=0.25,IDBUG=0)
c
      PARAMETER (IUIN=5,IUOUT=6,IERU=3)
C
C***end of include
