
c Variables required for WaterProperties.F Refer to www.iapws.org/refguide/iapws95.pdf.
      REAL RHO
      REAL T
      REAL IAPWSPRESS
      REAL IAPWSENERGY
      REAL IAPWSENTR
      REAL IAPWSENTH
      REAL IAPWSCV
      REAL IAPWSCP
      REAL CV
      REAL IAPWSSOUND
      REAL IAPWSSOUND2
      REAL IAPWSJOULE
      REAL IAPWSTHROTTLE
      REAL IAPWSBETA
      REAL IAPWSDPDR
      REAL P
      REAL IAPWSDPDT
      REAL dpdr
      REAL drho
      REAL limit
      REAL lim
      REAL p1
      REAL u1
      REAL u
      REAL dt
      REAL dpdt
      REAL beta
      REAL p2
      REAL s2
      REAL cp
      REAL dsdt
      REAL s
